version: '3'

services:
  mock-api:
    image: mock-api
    ports:
      - "6565:6565"
    build:
      context: ./mock-api
      dockerfile: Dockerfile

  master:
    image: locust
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master

  worker:
    image: locust
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
